name: Update holidays
on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 3 * *'
jobs:
  create_pull_request:
    permissions:
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
      - name: Update Holidays
        run: |
          python syukujitsu.py
          mv holidays.js js/
      - name: Commit
        id: commit
        continue-on-error: true
        run: |
          DATE=`date +"%Y%m%d"`
          BRANCH="update_$DATE"
          git config --local user.email "kumanofoo@gmail.com"
          git config --local user.name "kumanofoo"
          git add js/holidays.js
          git switch -c $BRANCH
          git commit -m "fix: update holidays"
          git push -f origin $BRANCH
      - name: Create Pull Request
        if: steps.commit.outcome == 'success'
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          gh pr create \
            --base main \
            --title "Update holidays" \
            --body "New holidays was released"
